title: "Your Name"
description: "Researcher / Professional / Writer"
url: ""
baseurl: ""

author:
  name: "Your Name"
  email: "you@example.com"

markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
